config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :books
  resources :directors
  resources :employees
  resources :shops
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books
  validates :name,:surname, presence: true
  validates :name,:surname, :format => { with: /[a-zA-Z ]+/,message: "allows only letters"}

end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :authors
  belongs_to :shop

  validates :title ,presence: true
  validates :published_at ,comparison: {greater_than: Date.new(1900,1,1)}

end

app/models/director.rb
class Director < ApplicationRecord
  belongs_to :shop

  validates :name,:surname,:salary ,presence: true
  validates :name,:surname, :format => { with: /[a-zA-Z ]+/,message: "allows only letters"}


end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :shop
  validates :name,:surname, :format => { with: /[a-zA-Z ]+/,message: "allows only letters"}
  validates :age , comparison: {greater_than: 18}

end

app/models/shop.rb
class Shop < ApplicationRecord

  validates :title , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ErrorHandling
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show,:update, :destroy]
  skip_before_action :verify_authenticity_token

  def index
    @authors = Author.all
    render json: @authors
  end

  def create
    @author = Author.new(authors_params)

    if !params[:books_id].nil? && params[:books_id]!=""
      params[:books_id].each do |book_id|
        @author.books << Book.find(book_id)
      end
    end
    if @author.save
      render json: @author, status: :created
    else
      render json: @author.errors, status: :unprocessable_entity
    end
    end


  def show
    render json: @author
  end

  def update

    if !params[:books_id].nil? && params[:books_id]!=""
      @author.books.delete
      params[:books_id].each do |book_id|
        @author.books << Book.find(book_id)
      end
    end
    @author.save
    @author.update(authors_params)
    head :ok
  end

  def destroy
    @author.books.each do |book|
      @author.books.destroy(book)
    end
    @author.delete
    head :ok
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def authors_params
    params.permit(:name, :surname, :style)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :update, :destroy]
  skip_before_action :verify_authenticity_token

  def index
    @books = Book.all
    render json: @books
  end

  def create
    @book = Book.new(books_params)
    if !params[:authors_id].nil? && params[:authors_id]!=""
      params[:authors_id].each do |author_id|
        @book.authors << Author.find(author_id)
      end
    end

    if @book.save
      render json: @book, status: :created
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  def show
    render json: @book
  end

  def update
    if !params[:authors_id].nil? && params[:authors_id]!=""
      @book.authors.delete
      params[:authors_id].each do |author_id|
        @book.authors << Author.find(author_id)
      end
      end
      @book.save
      @book.update(books_params)
      head :ok
    end
  end

  def destroy
    @book.authors.each do |author|
      @book.authors.destroy(author)
    end
    @book.delete
    head :ok
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def books_params
    params.permit(:title, :published_at, :theme, :shop_id)
  end

app/controllers/concerns/error_handling.rb
module ErrorHandling
  extend ActiveSupport::Concern
  included do

    rescue_from ActiveRecord::RecordNotFound,with: :notfound

    private

    def notfound(exception)
      render json: exception.message, status: 404
    end
  end

end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :update, :destroy]
  skip_before_action :verify_authenticity_token

  def index
    @directors= Director.all
    render json: @directors
  end

  def create
    @director = Director.new(directors_params)

    if @director.save
      render json: @director, status: :created
    else
      render json: @director.errors, status: :unprocessable_entity
    end
  end

  def show
    render json: @director
  end

  def update
    @director.update(directors_params)
    head :ok
  end

  def destroy
    @director.delete
    head :ok
  end

  private

  def set_director
    @director = Director.find(params[:id])
  end

  def directors_params
    params.permit(:name, :surname, :salary, :shop_id)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :update, :destroy]
  skip_before_action :verify_authenticity_token

  def index
    @employees= Employee.includes(:shop).all
    render json: @employees
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      render json: @employee, status: :created
    else
      render json: @employee.errors, status: :unprocessable_entity
    end
  end

  def show
    render @employee
  end

  def update
    @employee.update(employee_params)
    head :ok
  end

  def destroy
    @employee.delete
    head :ok
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  private

  def employee_params
    params.permit(:name, :surname, :age, :shop_id)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :update, :destroy]
  skip_before_action :verify_authenticity_token

  def index
    @shop= Shop.all
    render json: @shop
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      render json: @shop, status: :created
    else
      render json: @shop.errors, status: :unprocessable_entity
    end
  end

  def show
    render json: @shop
  end

  def update
    @shop.update(shop_params)
  end

  def destroy
    @shop.delete
  end

  private

  def set_shop
    @shop = Shop.find(params[:id])
  end

  private

  def shop_params
    params.permit(:title,:address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/authors/index.html.erb
<!--<!doctype html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--  <meta charset="UTF-8">-->
<!--  <title>authors</title>-->
<!--</head>-->
<!--<body>-->
<%#@authors.each do |author| %>
<!--<h3><%#=link_to("#{author.name},#{author.surname}",author_path(id: author.id))%></h3>-->
<%# end %>

<!--</body>-->
<!--</html>-->

app/views/authors/new.html.erb
<!--<!doctype html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--  <meta charset="UTF-8">-->
<!--  <title>newAuthor</title>-->
<!--</head>-->
<!--<body>-->
<!--<h1>Adding new author</h1>-->
<!--<h2>please, enter the following information</h2>-->

<!--<form method="post" action="/authors">-->
<!--  <label>name</label>-->
<!--  <input type="text" name="author[name]">-->
<!--  <label>surname</label>-->
<!--  <input type="text" name="author[surname]">-->
<!--  <label>style</label>-->
<!--  <input type="text" name="author[style]">-->
<!--  <button type="submit">submit</button>-->
<!--</form>-->
<!--</body>-->
<!--</html>-->

app/views/books/index.html.erb
<!--<!doctype html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--  <meta charset="UTF-8">-->
<!--  <title>authors</title>-->
<!--</head>-->
<!--<body>-->
<%#@books.each do |book| %>
<!--  <h3><%#=link_to(book.title ,book_path(id: book.id))%></h3>-->
<%# end %>

<!--</body>-->
<!--</html>-->

app/views/directors/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>authors</title>
</head>
<body>
<%@directors.each do |director| %>
  <h3><%=link_to("#{director.name}, #{director.surname}" ,director_path(id: director.id))%></h3>
<% end %>

</body>
</html>

app/views/employees/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>authors</title>
</head>
<body>
<%@employees.each do |employee| %>
  <h3><%=link_to("#{employee.name}, #{employee.surname}" ,employee_path(id: employee.id))%></h3>
<% end %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyTask3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shops/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>authors</title>
</head>
<body>
<%@shops.each do |shop| %>
  <h3><%=link_to(shop.title,shop_path(id: shop_id))%></h3>
<% end %>

</body>
</html>